image: ros:kinetic-robot

variables:
  ROS_PACKAGES_TO_INSTALL: ""
  USE_ROSDEP: "true"

catkin_build:
  stage: build
  script:
    - git clone https://git.ais.uni-bonn.de/nimbroshared/ros_gitlab_ci.git
    - source ros_gitlab_ci/gitlab-ci.bash
    - catkin build --summarize --no-status --force-color
    - source devel/setup.bash
    - ROS_TEST_RESULTS_DIR=$(pwd)/test_results catkin run_tests --no-status --force-color
    - find build -name test_results -type d -exec cp -R '{}' $CI_PROJECT_DIR/ ';' -print
  artifacts:
    paths:
      - test_results/
catkin_tools_tests:
  stage: test
  script:
    - ls -la
    - echo test_results/*/*.xml
    - git clone https://git.ais.uni-bonn.de/nimbroshared/ros_gitlab_ci.git
    - python ros_gitlab_ci/summarize_results.py test_results/*/*.xml test_results/summary.xml
